print('Instructor: Paul Anderson')
print('Caroline Oliver')
print('Joshua Glass')
print('Sam Word')
print('Kyle Glick')
print('Alex Giarrocco')
print('Tyler Newman')
print('Chase Hendley')
print('Zach Kidd')

